#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Clean up any compiled python files that might have been generated
        rm -rf /usr/share/gk-healter/src/__pycache__
        rm -rf /usr/share/gk-healter/src/*/__pycache__
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
